.TH colmap 1 "June 23 2017"
.SH NAME
colmap \- Structure-from-Motion and Multi-View Stereo
.SH SYNOPSIS
.B colmap
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B colmap
command.
.PP
\fBcolmap\fP is a general-purpose Structure-from-Motion (SfM) and Multi-View
Stereo (MVS) pipeline with a graphical and command-line interface. It offers
a wide range of features for reconstruction of ordered and unordered image
collections.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long options
starting with two dashes (`-'). A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.br
.SH ONLINE DOCUMENTATION
The program is documented at https://colmap.github.io/
