# COLMAP documentation build configuration file, created by
# sphinx-quickstart on Wed Jan 28 09:31:25 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import re
import subprocess

from sphinx.ext import autodoc


def get_git_revision():
    try:
        commit_id = (
            subprocess.check_output(["git", "rev-parse", "--short", "HEAD"])
            .decode()
            .strip()
        )
        commit_date = (
            subprocess.check_output(
                ["git", "log", "-1", "--format=%cd", "--date=short"]
            )
            .decode()
            .strip()
        )
        return f"{commit_id} ({commit_date})"
    except Exception:
        return "Unknown"


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.mathjax",
    "sphinx.ext.autodoc",
    "sphinx_design",
    "sphinx_sitemap",
    "sphinxext.opengraph",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "COLMAP"
copyright = "2026, COLMAP Team"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short MAJOR.MINOR.PATCH version.
version = "4.2.0.dev0" + " | " + get_git_revision()
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "logo": {
        "text": "COLMAP",
        "image_light": "_static/colmap-logo.svg",
        "image_dark": "_static/colmap-logo-dark.svg",
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/colmap/colmap",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/pycolmap/",
            "icon": "fa-brands fa-python",
        },
        {
            "name": "Docker Hub",
            "url": "https://hub.docker.com/r/colmap/colmap",
            "icon": "fa-brands fa-docker",
        },
    ],
    "navbar_align": "left",
    # Show nav links up to "Key Concepts"; collapse the rest into a "More" menu.
    "header_links_before_dropdown": 3,
    "navigation_with_keys": True,
    "show_prev_next": True,
    "pygments_light_style": "default",
    "pygments_dark_style": "monokai",
    "footer_start": ["copyright"],
    "footer_end": ["theme-version"],
}

# Follow the visitor's OS/browser preference for light/dark mode by default.
html_context = {"default_mode": "auto"}

# -- SEO -----------------------------------------------------------------

# Canonical site URL. Enables <link rel="canonical"> on every page (important
# because the hosted legacy/<version>/ copies are near-duplicate content) and is
# the base URL used for the sitemap and Open Graph tags.
html_baseurl = "https://colmap.github.io/"

# sphinx-sitemap: the docs are not multi-version/multi-language, so emit plain
# page URLs (no {version}/{lang} path segments).
sitemap_url_scheme = "{link}"

# sphinxext-opengraph: Open Graph / Twitter card metadata + meta description.
ogp_site_url = html_baseurl
ogp_site_name = "COLMAP"
ogp_description_length = 200
ogp_enable_meta_description = True
ogp_image = "https://colmap.github.io/_static/og-image.png"
ogp_image_alt = "COLMAP — Structure-from-Motion & Multi-View Stereo"
ogp_use_first_image = False
ogp_custom_meta_tags = [
    '<meta name="twitter:card" content="summary_large_image" />',
]

# Copy robots.txt (which points crawlers to the sitemap) to the site root.
html_extra_path = ["robots.txt"]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "COLMAP"

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/colmap-logo.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.
html_favicon = "_static/favicon.svg"

# Give the landing page a full-width layout by dropping the left sidebar.
html_sidebars = {"index": []}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["custom.css", "landing.css"]
html_js_files = ["install_selector.js"]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = "COLMAPdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'a4paper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        "index",
        "COLMAP.tex",
        "COLMAP Documentation",
        "Johannes L. Schoenberger",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
latex_show_urls = "footnote"

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = False


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        "index",
        "colmap",
        "COLMAP Documentation",
        ["Johannes L. Schoenberger"],
        1,
    )
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "COLMAP",
        "COLMAP Documentation",
        "Johannes L. Schoenberger",
        "COLMAP",
        "Structure-from-Motion and Multi-View Stereo.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

# Configure how Python API docs are displayed.
autoclass_content = "both"
autodoc_member_order = "bysource"
autodoc_typehints = "both"
python_maximum_signature_line_length = 120
autodoc_use_legacy_class_based = True


def sort_members(
    self, documenters: list[tuple[autodoc.Documenter, bool]], order: str
) -> list[tuple[autodoc.Documenter, bool]]:
    """Order the members by their definition order."""
    class_names = list(self.object.__dict__)

    def keyfunc(entry: tuple[autodoc.Documenter, bool]) -> int:
        name = entry[0].name.split("::")[1].split(".")[1]
        if name in class_names:
            return class_names.index(name)
        else:
            return len(class_names)

    documenters.sort(key=keyfunc)
    return documenters


# autodoc_member_order=bysource does not work for C++-defined classes since they
# cannot be introspected and do not have an __all__ list. Instead,
# we extract the definition order from object.__dict__.
autodoc.ClassDocumenter.sort_members = sort_members


def process_doc(app, what, name, obj, options, lines):
    if not lines:
        return
    has_overload = lines[0] == "Overloaded function."
    for i in range(len(lines)):
        lines[i] = lines[i].replace("pycolmap._core", "pycolmap")
        if has_overload and re.search(r"^\d+\. ", lines[i]):
            index, signature = lines[i].split(". ", 1)
            signature = "``" + signature.replace("->", "→") + "``"
            lines[i] = ". ".join([index, signature])


def process_sig(app, what, name, obj, options, signature, return_annotation):
    if signature is None:
        return None, return_annotation
    signature = signature.replace("pycolmap._core", "pycolmap")
    if isinstance(return_annotation, str):
        return_annotation = return_annotation.replace(
            "pycolmap._core", "pycolmap"
        )
    return signature, return_annotation


def setup(app):
    # Remap types from the C++ module pycolmap._core to the Python namespace.
    app.connect("autodoc-process-docstring", process_doc)
    app.connect("autodoc-process-signature", process_sig)
