language: cpp

os:
  - linux
#  - osx

dist: trusty
sudo: required

compiler:
#  - clang
  - gcc

#env:
#  - CONFIG=Release
#  - CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
#  - sudo apt-get upgrade -y
  - sudo apt-get install g++-6 -y
#  - sudo rm -f /usr/bin/gcc
#  - sudo rm -f /usr/bin/g++
#  - sudo cp -f /usr/bin/gcc-6 /usr/bin/gcc
#  - sudo cp -f /usr/bin/g++-6 /usr/bin/g++
#  - sudo rm -f /usr/bin/clang
#  - sudo rm -f /usr/bin/clang++
#  - sudo cp -f /usr/bin/clang-3.8 /usr/bin/clang
#  - sudo cp -f /usr/bin/clang++-3.8 /usr/bin/clang++
  - wget http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.bz2
  - tar jxf boost_1_64_0.tar.bz2
  - sudo cp -r boost_1_64_0/boost /usr/local/include

install:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - $CXX --version
#  - clang++ --version
  - cmake --version

before_script:
  - cd $TRAVIS_BUILD_DIR/tests/base
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - cd $TRAVIS_BUILD_DIR/tests/base/build
  - cmake --build . --config Release
  - ./yas-base-test binary
