parameters:
  displayName: Mac 10.15
  macVersion: '10.15'
  
jobs:
- job: mac_build_${{ replace(parameters.macVersion, '.', '') }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'macOS-${{ parameters.macVersion }}'
  variables:
    CCACHE_DIR: $(Pipeline.Workspace)/ccache
    CCACHE_BASEDIR: $(Build.SourcesDirectory)
    CCACHE_VERSION: 1
  steps:
  - script: |
      brew install \
        cmake \
        ninja \
        boost \
        eigen \
        flann \
        freeimage \
        metis \
        glog \
        googletest \
        ceres-solver \
        qt5 \
        glew \
        cgal \
        sqlite3 \
        ccache
    displayName: Install dependencies

  - task: Cache@2
    inputs:
      key: ccache | "$(CCACHE_VERSION)" | "$(Agent.OS)" | "${{ parameters.displayName }}" | "$(Build.BuildNumber)"
      restoreKeys: ccache | "$(CCACHE_VERSION)" | "$(Agent.OS)" | "${{ parameters.displayName }}"
      path: $(CCACHE_DIR)
    displayName: Restore CCache

  - script: |
      export PATH="/usr/local/opt/qt@5/bin:$PATH"
      cmake --version
      mkdir build
      cd build
      cmake .. \
        -GNinja \
        -DTESTS_ENABLED=ON \
        -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5
      ninja
    displayName: Configure and build

  - script: |
      cd build
      ctest
      tests_pass=$?
      if [ $tests_pass -ne 0 ]; then
          echo "\n\n\nTests failed, rerunning with verbose output"
          ctest --rerun-failed --output-on-failure
      fi
      exit $tests_pass
    displayName: Run tests

  - script: |
      set -x
      ccache --show-stats
      ccache --evict-older-than 1d
      ccache --show-stats
    displayName: Cleanup ccache
