parameters:
  displayName: 'Docker'

jobs:
- job: docker_build
  displayName: '${{ parameters.displayName }}'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    DOCKER_BUILDKIT: 1
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      CudaArchs: 50
    ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      # TODO: With CMake 3.23, we can set "all-major" instead.
      CudaArchs: 50;60;70;75;90
  steps:
  - bash: |
      echo "Building git commit: $(Build.SourceVersion)"
    displayName: "Log git commit"

  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      arguments: --build-arg COLMAP_GIT_COMMIT=$(Build.SourceVersion) --build-arg CUDA_ARCHITECTURES=$(CudaArchs)
      Dockerfile: docker/Dockerfile
      repository: colmap/colmap
      tags: |
        latest
        $(Build.BuildNumber)

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhub-colmap

    - task: Docker@2
      displayName: Push to Docker Hub
      inputs:
        command: push
        repository: colmap/colmap
        tags: |
          latest
          $(Build.BuildNumber)
