parameters:
  displayName: 'Docker'

jobs:
- job: docker_build
  displayName: '${{ parameters.displayName }}'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    DOCKER_BUILDKIT: 1
  steps:
  - bash: |
      echo "Building git commit: $(Build.SourceVersion)"
    displayName: "Log git commit"

  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      arguments: --build-arg COLMAP_GIT_COMMIT=$(Build.SourceVersion) --build-arg CUDA_ARCHITECTURES=50
      Dockerfile: docker/Dockerfile
